### ISSUE TITLE
Broken in puma 3.1

### ISSUE THREAD

**Issue by jeffblake** [hired/puma-stats-logger#2]
This is what I'm getting using the standard configuration, on Heroku.

```
NoMethodError (undefined method `options' for nil:NilClass):
vendor/bundle/ruby/2.3.0/gems/puma-stats-logger-0.2.1/lib/puma_stats_logger/middleware.rb:19:in `puma_options'
vendor/bundle/ruby/2.3.0/gems/puma-stats-logger-0.2.1/lib/puma_stats_logger/middleware.rb:10:in `call'
```

**Comment by heythisisnate** [comment]
Yep, I'm getting the same error. Puma 3.1 wasn't on my radar, thanks for bringing this to our attention. I'll look into a fix for this.

**Comment by jeffblake** [comment]
Thanks. I ended up re-evaluating how I monitor Puma. I've switched it to a clock process using rufus-scheduler so that it doesn't interfere with any requests.

**Comment by heythisisnate** [comment]
Good call. I briefly looked into this and I agree that a different approach to monitoring puma is necessary. _Especially_ if you're using Puma's cluster mode (which we now are), it doesn't make sense at all to using this middleware on every request.

@jeffblake I assume you're using Heroku. If you have multiple dynos on Heroku, how are you able to get Puma stats from each dyno when using an external clock process?

**Comment by jeffblake** [comment]
I put it in an initializer. So it runs within the dyno. Perhaps not ideal, but its the only method I could think of.

here's the source

```
require 'rufus-scheduler'

# Let's use the rufus-scheduler singleton
#
s = Rufus::Scheduler.singleton

PUMA_STATE_FILE = 'tmp/puma.state'
PUMA_CONTROL_URL = 'control_url'
PUMA_CONTROL_TOKEN = 'control_auth_token'

if ENV['PUMA']
  config = Librato.tracker.config
  Librato::Metrics.authenticate config.user, config.token
  queue = Librato::Metrics::Queue.new
  source = config.source

  s.every '2s' do

    begin

      config = YAML.load_file(PUMA_STATE_FILE)
      return unless config

      control_url = config[PUMA_CONTROL_URL]
      socket = control_url.gsub('unix://'.freeze, ''.freeze)
      token = config[PUMA_CONTROL_TOKEN]

      s = UNIXSocket.new socket
      s << "GET /stats?token=#{token} HTTP/1.0\r\n\r\n"
      body = s.read

      status = HashWithIndifferentAccess.new JSON.parse( body.split("\r\n".freeze).last )

      queue.add :'puma.workers' => { value: status[:workers], source: source }
      queue.add :'puma.booted_workers' => { value: status[:booted_workers], source: source }

      status[:worker_status].each do |worker|
        worker_source = [source, worker[:index]].join('.'.freeze)
        status = worker.dig(:last_status)
        backlog = status.dig(:backlog) || 0
        running = status.dig(:running) || 0

        queue.add :'puma.backlog' => { value: backlog, source: worker_source }
        queue.add :'puma.running' => { value: running, source: worker_source }

      end

      queue.submit

      # Librato.group 'puma' do |g|
      #   g.measure 'backlog', backlog, source: source
      #   g.measure 'running', running, source: source
      # end
      # Librato.group 'puma' do |g|
      #   g.measure 'workers', status[:workers]
      #   g.measure 'booted_workers', status[:booted_workers]
      # end

    rescue Errno::ENOENT => e
      $stdout.puts('unable to load yaml file')

    end

  end

end

```

This gives me nice, consistent stats, with each worker tagged as its own unique source in Librato. e.g. `production.web.1.5`

**Comment by jeffblake** [comment]
And in the procfile:

`web: env PUMA=true rake db:schema:cache:dump && bin/start-pgbouncer-stunnel bundle exec puma -C config/puma.rb`

There's probably a better way to detect if the process in running in Puma...

**Comment by heythisisnate** [comment]
This is pretty clever. Are you using Puma's cluster mode? I'm not familiar with Rufus Scheduler, but it seems like in cluster mode with multiple Puma processes running, you'd have multiple schedulers running, to0. Is that the case?

**Comment by jeffblake** [comment]
Hmm. Yes I'm in cluster mode. 

You're right... I tested it again. So it appears that exactly two rufus-schedulers are executed, regardless of the number of workers I have set. Thats better than 16 reporting per dyno... but still not ideal. Any ideas?

**Comment by heythisisnate** [comment]
I would expect that there would be one scheduler running per_worker_ (not per thread). This is because each worker is a new copy of the app in memory, so I believe each worker will have it's own RufusScheduler singleton. What's your puma config look like? How many workers vs threads do you have configured and on which dyno type?

**Comment by jeffblake** [comment]
I agree, that was my hypothesis going into the test. But no matter how many workers I scaled up, there were always only 2 rufus' reporting.

I run on PX dynos, with 16 workers and 8 threads.

```
workers ENV.fetch('SCALE_WORKERS') { 2 }.to_i
threads_count = ENV.fetch('SCALE_THREADS') { 5 }.to_i
threads threads_count, threads_count

# DB_POOL should be equal to max threads

preload_app!

rackup      DefaultRackup
port        ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RACK_ENV') { 'development' }

activate_control_app
state_path 'tmp/puma.state'

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
after_worker_boot do

end
before_fork do
  ActiveRecord::Base.connection_pool.disconnect!
end
```
